---
- name: A few basic filters
  hosts: localhost
  gather_facts: no


  vars:
    jarlist: [1,1,1,1,1,5]
    repeatlist: [1,2,2,2,4,4,4,4,9,9,9,9]
    repeat2list: [5,5,5,5,5,6,7]
    complexlist: [6,7,8,[9,10,22],87]

  tasks:
  - name: The min filter
    debug:
      msg: "Show me the lowest number ins the list: '{{jarlist|min}}'"

  - name: Max list
    debug:
      msg: "SHow the me largetst numer in the list: '{{jarlist|max}}'"

  - name: the faltten filter
    debug:
      msg: "THe list was complex '{{complexlist}}' but now it is not '{{complexlist|flatten}}'"

  - name:  the flatten filter used with looping
    debug:
      msg: 'We just want to use the items for the list {{item}}'
    loop: "{{complexlist|flatten}}"

  - name: get  unique set from a list
    debug:
      msg: 'We just want the unique set from a list {{repeatlist|unique}}'

  - name: produce a list union from two lists
    debug:
      msg: 'Display the union of the lists {{repeatlist|union(repeat2list)}}'

  - name: show the diffs betwen two lists
    debug:
      msg: 'Display the diffs of two lists {{repeatlist|difference(repeat2list)}}'
