---
- name: Agnostic Net Example
  hosts: all
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_eos: eos
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: admin
    ansbile_ssh_pass: alta3

    tasks:
      - name: run show version on remote devices
        cli_command:
          command: show version
