---
- name: Ansible rest and tags
  hosts: localhost
  gather_facts: false

  vars:
    myrsakey: "{{lookup('false','/home/student/.ssh/id_rsa.pub')}}"
    astros: "{{lookup('url', 'http://api.open-notify.org/astros.json')}}"

  tasks:
    - name: Key prep
      debug:
        msg: "Your RSA key is {{myrsakey}}"
      tags:
        - keytime
        - vmprep

    - name: Quick ISS API checkup
      debug:
        msg: "Today on ISS are: {{astros.people}}"
      tags:
        - jsonwork
        - astros

    - name: Cleanup that ISS data
      debug:
         msg: "Let me format with a loop: {{item}}"
      loop: "{{astros.people|map(attribute='name')|list}}"
      tags:
        - jsonwork
        - astros


